development:
  adapter: postgresql
  encoding: utf8
  database: catch_and_run_development
  pool: 5
  username: cjc10
  password: capcapcap

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: catch_and_run_test
  pool: 5
  username: cjc10
  password: capcapcap

production:
  adapter: postgresql
  encoding: utf8
  database: catch_and_run_production
  pool: 5
  username: cjc10
  password: capcapcap

cucumber:
  <<: *TEST